src/objects/PIA_R__c.object
<CustomObject>
    <label>PIA_R</label>
    <nameField>
        <label>番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIA_SUM__c.object
<CustomObject>
    <fields>
        <fullName>dankai_atari10__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階10当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari11__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階11当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari12__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階12当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari13__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階13当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari14__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階14当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari2__c</fullName>
        <formula>beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階02当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari3__c</fullName>
        <formula>beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階03当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari4__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階04当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari5__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階05当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari6__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階06当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari7__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階07当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari8__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階08当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari9__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.dankai_atari__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>段階09当たり</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dankai_atari__c</fullName>
        <label>段階01当たり</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hyoujijunn__c</fullName>
        <label>表示順</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>renritucompare10__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較10</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare11__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較11</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare12__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較12</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare13__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較13</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare14__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較14</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare2__c</fullName>
        <formula>beforce__r.renritucompare__c</formula>
        <label>連率比較02</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare3__c</fullName>
        <formula>beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較03</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare4__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較04</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare5__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較05</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare6__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較06</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare7__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較07</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare8__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較08</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare9__c</fullName>
        <formula>beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.beforce__r.renritucompare__c</formula>
        <label>連率比較09</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>renritucompare__c</fullName>
        <description>TRUE:よくない</description>
        <formula>Field2__c &lt; Field4__c</formula>
        <label>連率比較01</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sum_atari__c</fullName>
        <label>集計_当たり</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sum_kaiten__c</fullName>
        <label>集計_回転数</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sum_tuujou__c</fullName>
        <label>集計_通常</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PIA_SUM</label>
    <nameField>
        <label>台番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIADATA__c.object
<CustomObject>
</CustomObject>

src/classes/TestPiaData_Dankai_After_R.cls
global class TestPiaData_Dankai_After_R implements Database.Batchable<sObject>, Database.Stateful {

    public String query;
    public String taiNo = '';
    public Decimal adate = 0;

    Public static String PIA_END_NO = System.Label.PIA_END_NO;

    global TestPiaData_Dankai_After_R(String taibangou) {
        // 台番号設定
        this.taiNo = taibangou;
    	this.query = 'SELECT' +
        ' renritucompare__c,' +
        ' renritucompare2__c,' +
        ' renritucompare3__c,' +
        ' renritucompare4__c,' +
        ' renritucompare5__c,' +
        ' renritucompare6__c,' +
        ' renritucompare7__c,' +
        ' renritucompare8__c,' +
        ' renritucompare9__c,' +
        ' renritucompare10__c,' +
        ' renritucompare11__c,' +
        ' renritucompare12__c,' +
        ' renritucompare13__c,' +
        ' renritucompare14__c,' +
        ' dankai_atari__c,' +
        ' dankai_atari2__c,' +
        ' dankai_atari3__c,' +
        ' dankai_atari4__c,' +
        ' dankai_atari5__c,' +
        ' dankai_atari6__c,' +
        ' dankai_atari7__c,' +
        ' dankai_atari8__c,' +
        ' dankai_atari9__c,' +
        ' dankai_atari10__c,' +
        ' dankai_atari11__c,' +
        ' dankai_atari12__c,' +
        ' dankai_atari13__c,' +
        ' dankai_atari14__c,' +
        ' sum_atari__c,' +
        ' sum_kaiten__c,' +
        ' sum_tuujou__c,' +
        ' Name,' +
        ' Id ' +
        ' FROM PIA_SUM__c' +
        ' WHERE Name = :taiNo' +
        ' AND hyoujijunn__c = 1';

        // 最新データの日付を取得する
        PIADATA__c pia =[SELECT id, adate__c FROM piadata__c where Name = :taibangou ORDER BY adate__c DESC LIMIT 1];
        this.adate = pia.adate__c;
        // 既存の最新データを物理削除する
		List<PIA_R__c> dellist = [SELECT Id FROM PIA_R__c WHERE adate__c = :adate AND Name = :taibangou];
        // 削除処理
		if (dellist.size() > 0){
		    Delete dellist;
		    Database.emptyRecycleBin(dellist);
        } 
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<PIA_SUM__c> scope) {

        List<PIA_R__c> listb = new List<PIA_R__c>();
        for(PIA_SUM__c piasum : scope){
            PIA_R__c pia_r = new PIA_R__c();
            pia_r.renritucompare__c = piasum.renritucompare__c;
            pia_r.renritucompare2__c = piasum.renritucompare2__c;
            pia_r.renritucompare3__c= piasum.renritucompare3__c;
            pia_r.renritucompare4__c= piasum.renritucompare4__c;
            pia_r.renritucompare5__c= piasum.renritucompare5__c;
            pia_r.renritucompare6__c= piasum.renritucompare6__c;
            pia_r.renritucompare7__c= piasum.renritucompare7__c;
            pia_r.renritucompare8__c= piasum.renritucompare8__c;
            pia_r.renritucompare9__c= piasum.renritucompare9__c;
            pia_r.renritucompare10__c= piasum.renritucompare10__c;
            pia_r.renritucompare11__c= piasum.renritucompare11__c;
            pia_r.renritucompare12__c= piasum.renritucompare12__c;
            pia_r.renritucompare13__c= piasum.renritucompare13__c;
            pia_r.renritucompare14__c= piasum.renritucompare14__c;
            pia_r.dankai_atari__c= piasum.dankai_atari__c;
            pia_r.dankai_atari2__c= piasum.dankai_atari2__c;
            pia_r.dankai_atari3__c= piasum.dankai_atari3__c;
            pia_r.dankai_atari4__c= piasum.dankai_atari4__c;
            pia_r.dankai_atari5__c= piasum.dankai_atari5__c;
            pia_r.dankai_atari6__c= piasum.dankai_atari6__c;
            pia_r.dankai_atari7__c= piasum.dankai_atari7__c;
            pia_r.dankai_atari8__c= piasum.dankai_atari8__c;
            pia_r.dankai_atari9__c= piasum.dankai_atari9__c;
            pia_r.dankai_atari10__c= piasum.dankai_atari10__c;
            pia_r.dankai_atari11__c= piasum.dankai_atari11__c;
            pia_r.dankai_atari12__c= piasum.dankai_atari12__c;
            pia_r.dankai_atari13__c= piasum.dankai_atari13__c;
            pia_r.dankai_atari14__c= piasum.dankai_atari14__c;
            pia_r.sum_atari__c= piasum.sum_atari__c;
            pia_r.sum_kaiten__c= piasum.sum_kaiten__c;
            pia_r.sum_tuujou__c= piasum.sum_tuujou__c;
            pia_r.Name= piasum.Name;
            pia_r.adate__c= this.adate;
            listb.add(pia_r);
        }
        insert listb;
    }

    global void finish(Database.BatchableContext BC) {

        //３日前のデータを残る
		Decimal adateTmp = getDataTimeByStrYm(this.adate, 8);
        // 台番号
		String taibangouTmp = this.taiNo;

        List<PIA_R__c> dellist = [SELECT Id FROM PIA_R__c WHERE adate__c <= :adateTmp AND Name = :taibangouTmp];
        if (dellist.size() > 0){
            Delete dellist;
            Database.emptyRecycleBin(dellist);
        }
        // サマリーデータを削除する
        List<PIA_SUM__c> dellistSum = [SELECT Id FROM PIA_SUM__c WHERE Name = :taibangouTmp];
        if (dellistSum.size() > 0){
            Delete dellistSum;
            Database.emptyRecycleBin(dellistSum);
        } 


        //次の台の処理へ
        String tmpTaiNo = String.valueOf(Integer.valueOf(taibangouTmp) + 1);
        // if (tmpTaiNo == '705'){
        //     tmpTaiNo = '717';
        // }
        if (this.taiNo != PIA_END_NO){
            TestPiaData_Dankai_R newbatch = new TestPiaData_Dankai_R(tmpTaiNo);
            Database.executeBatch(newbatch);
        }else{
   
            RunOver newbatch = new RunOver();
            Database.executeBatch(newbatch);
        }
    }

    private Decimal getDataTimeByStrYm(Decimal ym, Integer plusMonthNum) {
        String strYm = '20' + String.valueOf(ym.intValue());
        Date inputDate = Date.newInstance(Integer.valueof(strYm.substring(0,4)), Integer.valueof(strYm.substring(4,6)), Integer.valueof(strYm.substring(6)));
        inputDate = inputDate.addDays(plusMonthNum * -1);
        DateTime rs = DateTime.newInstance(inputDate, Time.newInstance(0, 0, 0, 0));
        return Decimal.valueOf(rs.format('yyMMdd'));
    }
}