src/objects/PIA_SUM__c.object
<CustomObject>
    <fields>
        <fullName>beforce__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>前段階</label>
        <referenceTo>PIA_SUM__c</referenceTo>
        <relationshipLabel>PIA_SUM</relationshipLabel>
        <relationshipName>PIA_SUM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>hyoujijunn__c</fullName>
        <label>表示順</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PIA_SUM</label>
    <nameField>
        <label>台番号</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPiaData_Dankai_beforce_R.cls
global class TestPiaData_Dankai_beforce_R implements Database.Batchable<sObject>,Database.Stateful {

    public String query;
    public String taiNo = '';
    Public static String PIA_END_NO = System.Label.PIA_END_NO;
    global TestPiaData_Dankai_beforce_R(String taibangou) {
        this.taiNo = taibangou;
        this.query = 'SELECT id FROM PIA_SUM__c WHERE name=:taiNo ORDER BY hyoujijunn__c DESC' ;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<PIA_SUM__c> scope) {
        Integer index2 = -1;

        for(PIA_SUM__c pia : scope){
            if(index2 >= 0){
                PIA_SUM__c piaTmp = (PIA_SUM__c)(scope.get(index2));
                pia.beforce__c = piaTmp.Id;
            }
            index2 = index2 + 1;
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC) {
        TestPiaData_Dankai_After_R newbatch = new TestPiaData_Dankai_After_R(this.taiNo);
        Database.executeBatch(newbatch);
    }
}